version: 1
services:
  - type: web
    name: my-php-app
    env: docker
    docker:
      dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "apache2-foreground"
    env:
      DB_HOST: "localhost"
      DB_NAME: "student"
      DB_USER: "adrian"
      DB_PASS: ""
    healthCheck:
      path: /
      interval: 10s
      timeout: 5s
      healthyThreshold: 2
      unhealthyThreshold: 3
